name: Installation Test

on:
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  test-installation:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SuperShell
        env:
          SHELL: /bin/zsh
        run: |
          echo "Current SHELL: $SHELL"
          echo "Shell RC path will be: $HOME/.$(basename $SHELL)rc"
          
          # Run the automatic installation
          curl -sL https://raw.githubusercontent.com/2501-ai/supershell/refs/heads/main/install.sh | zsh

      - name: Verify Installation
        env:
          SHELL: /bin/zsh
        run: |
          # Check if SuperShell directory exists
          echo "Checking if SuperShell directory exists..."
          if [ ! -d "$HOME/.supershell" ]; then
            echo "Error: SuperShell installation directory not found"
            exit 1
          fi
          
          # Check if main.sh is sourced in .zshrc
          echo "Checking if main.sh is sourced in .zshrc..."
          if ! grep -q "source.*\.supershell/main.sh" "$HOME/.zshrc"; then
            echo "Error: main.sh is not sourced in .zshrc"
            echo "Contents of .zshrc:"
            cat "$HOME/.zshrc"  # Add this for debugging
            exit 1
          fi 